server:
  port: 8000
  ssl:
    enabled: false

spring:
  datasource.url: x
  security.oauth2.client.registration.github.client-id: Iv1.68c92063aa61085c
  security.oauth2.client.registration.github.client-secret: x

objectStorage:
  imageBucket:
    accessKeyId: x
    secretAccessKey: x

site:
  url: http://localhost:8000
