server:
  port: 8000
  ssl:
    enabled: false

spring:
  datasource:
    url: x

security:
  oauth2:
    client:
      clientId: Iv1.68c92063aa61085c
      clientSecret: x

objectStorage:
  imageBucket:
    accessKeyId: x
    secretAccessKey: x

site:
  url: http://localhost:8000
