server:
  port: 8000
  ssl:
    enabled: false

spring:
  datasource.url: jdbc:postgresql://localhost:5432/zack
  datasource.username: zack
  datasource.password: zack

objectStorage:
  imageBucket:
    name: images
    url: http://localhost:4566
    region: us-west-2
    accessKeyId: x
    secretAccessKey: x

site:
  url: http://localhost:8000

userAuthorization.userPermissions:
  zrbrown: ADMIN, POST_ADMIN, POST_ADD, POST_EDIT, POST_UPDATE