server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: /etc/keystore.p12
#    key-store-password:
#    keyStoreType: PKCS12
#    keyAlias: tomcat

spring:
  freemarker.template-loader-path: classpath:/templates
  freemarker.suffix: .ftl
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.17.0.2:5432/zackrbrown_com
    username: postgres
    password: postgres
  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    default_schema: application
    jdbc.lob.non_contextual_creation: true

security:
#  require-ssl: true
#  oauth2:
#    client:
#      clientId: bd1c0a783ccdd1c9b9e4
#      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://api.github.com/user
