spring:
  security.oauth2.client.registration.github.client-id: Iv1.a4cf7da0a75e9d81

objectStorage:
  imageBucket:
    name: zackrbrown
    url: https://nyc3.digitaloceanspaces.com
    region: nyc3

site.url: https://zackrbrown.com

staticContent.markdownToName:
  projects: Projects
  about: About

userAuthorization.userPermissions:
  zrbrown: ADMIN, POST_ADMIN, POST_ADD, POST_EDIT, POST_UPDATE

friendly-ssl:
  domain: zackrbrown.com
  account-email: zackrbrown@gmail.com
