server:
  port: 443
  ssl:
    enabled: true
    key-store: /etc/keystore.p12
    key-store-password: 
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  freemarker.template-loader-path: classpath:/templates
  freemarker.suffix: .ftl
  datasource:
    platform: postgres
    url: jdbc:postgresql://<url>
    username: <user>
    password: <pw>
  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    default_schema: application
    jdbc.lob.non_contextual_creation: true

security:
  require-ssl: true
  oauth2:
    client:
      clientId: Iv1.a4cf7da0a75e9d81
      clientSecret: <secret>
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
