spring.jpa.properties.hibernate.default_schema: application

security.oauth2.client.clientId: Iv1.a4cf7da0a75e9d81

objectStorage:
  imageBucket:
    name: images
    url: https://zackrbrown.nyc3.digitaloceanspaces.com
    region: nyc3

site:
  url: https://zackrbrown.com
  authorizedUsers: [zrbrown]

staticContent.markdownToName:
  projects: Projects
  about: About
