server:
  port: 8080

spring.freemarker.template-loader-path: classpath:/templates
spring.freemarker.suffix: .ftl

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.17.0.2:5432/zackrbrown_com
    username: postgres
    password: postgres
