server:
  port: 8080

spring.freemarker.template-loader-path: classpath:/templates
spring.freemarker.suffix: .ftl

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.56.111:5432/postgres
    username: postgres
    password:
